library(drake)
library(purrr)
library(data.table)
library(ingestr)
library(httr)
library(lme4)
library(tydygraphs)
library(ggplot2)
library(fs)
library(stringr)
library(mcp)
library(broom)
library(errors)
library(glmnet)
library(fst)
library(disk.frame)
library(parallel)

setup_disk.frame(4)
options(future.globals.maxSize = Inf)
setDTthreads(2)
threads_fst(2)
options(future.supportsMulticore.unstable = TRUE,
        mc.cores = 4)